# Generated by Django 4.0.4 on 2022-05-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageNFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generator_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('data', models.TextField()),
                ('image_url', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
