# Generated by Django 4.0.4 on 2022-05-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenft',
            name='generator_id',
        ),
    ]
