# Generated by Django 4.0.4 on 2022-05-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0002_remove_imagenft_generator_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenft',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('generated', 'Generated'), ('error', 'Error')], default='created', max_length=10),
        ),
    ]
