# Generated by Django 4.0.4 on 2022-05-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0003_imagenft_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenft',
            name='error',
            field=models.TextField(default=''),
        ),
    ]
