# Generated by Django 4.0.4 on 2022-05-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0004_imagenft_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenft',
            name='user',
            field=models.CharField(default='None', max_length=300),
        ),
    ]
